spring:
   application:
      name: eurekaservice
server:
   port: 8761
   
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      
      # Comment below line for production
      server:
         waitTimeInMsWhenSyncEmpty: 5
      
logging:
   # Emit logs to file with standard spring log patterns.
   # This is so SBA can consume and display logs
   path: 'logs/'
   file: '${logging.path}/application.log'
   pattern.file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
   level:
      com:
         netflix:
            eureka: "OFF"
            discovery: "OFF"