spring:
   application:
      name: eurekaservice
server:
   port: 8761
   
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
      
      # Comment below line for production
      server:
         waitTimeInMsWhenSyncEmpty: 5
      
logging:
   level:
      com:
         netflix:
            eureka: "OFF"
            discovery: "OFF"